# -*- coding: utf-8 -*-
"""Minimalistic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zVN8--zCKgYYF7pknec4zXNGGN7JjAH0
"""

#!pip install pytube
#!pip install SpeechRecognition
#!pip install sumy
#!pip install nltk
#!pip install pydub
#!pip install youtube_dl
#!pip install transformers
#!pip install vosk
#!wget https://alphacephei.com/vosk/models/vosk-model-en-us-aspire-0.2.zip
#!unzip vosk-model-en-us-aspire-0.2.zip
#!pip install youtube-transcript-api

#gets the transcript from s youtube link
def save_transcript_to_file(transcript, filename="transcript.txt"):
    with open(filename, "w", encoding="utf-8") as f:
        f.write(transcript)

import re
from youtube_transcript_api import YouTubeTranscriptApi

def extract_video_id(url):
    video_id_regex = r"(?:https?:\/\/)?(?:www\.)?(?:youtube\.com\/(?:watch\?v=|embed\/)|youtu\.be\/)([^&]+)"
    match = re.search(video_id_regex, url)
    if match:
        return match.group(1)
    else:
        return None
def get_transcript(video_id):
    try:
        transcript = YouTubeTranscriptApi.get_transcript(video_id, languages=['en'])
        transcript_text = ' '.join([entry['text'] for entry in transcript])
        return transcript_text
    except Exception as e:
        print(f"Error: {e}")
        return None

'''
url = input("Enter the YouTube video URL: ")
video_id = extract_video_id(url)

if video_id:
    transcript = get_transcript(video_id)
    if transcript:
        print(transcript)
        save_transcript_to_file(transcript)
        print("Transcript saved to 'transcript.txt'")
    else:
        print("Could not get the transcript")
else:
    print("Invalid YouTube URL")
'''